---
extends: airbnb
env:
  node: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    es6: true
    jsx: true
    modules: true
rules:
  comma-dangle:
  - 2
  - always-multiline
  no-use-before-define: 0
  react/jsx-filename-extension: 0
  arrow-parens:
  - 2
  - always
  react/require-default-props: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0
  react/sort-comp: 0
  react/prop-types: 0
  react/no-danger: 0
  max-len:
  - 0
  - 120
globals: {}
settings:
  import/resolver:
    babel-module: {}
